# General Parameters

debug = true

# Geometry

receivers = "data/input/geometry/receivers.txt"
sources = "data/input/geometry/sources.txt" 

offset = 5 # [m]

# Model

model_path = "data/input/models/model_2layer_200x100.bin"

nx = 200
nz = 100

dh = 10.0

nb     = 100
factor = 0.009

# Seismogram

perc = 99

save_residual = true

nt = 2001
dt = 1.0e-3

# Wavelet

fmax = 30.0
tlag = 0.3



